version: '3.8'

volumes:
  postgres-data:
  grafana-data-config-datasources:
  grafana-data-config-dashboards:
  grafana-data-dashboards:

networks:
  back-tier:

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - ../.env
    volumes:
      - ../:/workspaces/project-NicolaiDG
      - grafana-data-config-datasources:/workspaces/project-NicolaiDG/.grafana/datasources
      - grafana-data-config-dashboards:/workspaces/project-NicolaiDG/.grafana/dashboards
      - grafana-data-dashboards:/workspaces/project-NicolaiDG/dashboards
    networks:
      - back-tier
    depends_on:
      - db
      - grafana
      - adminer
    command: sleep infinity

  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ../.env
    ports:
      - "5434:5432"  # Changed port to 5434
    networks:
      - back-tier

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"  # Changed port to 8081
    networks:
      - back-tier

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    volumes:
      - grafana-data-config-datasources:/etc/grafana/provisioning/datasources:ro
      - grafana-data-config-dashboards:/etc/grafana/provisioning/dashboards:ro
      - grafana-data-dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    networks:
      - back-tier
    user: "472"
