version: '3.8'

volumes:
  postgres-data:
  grafana-data-config-datasources:
  grafana-data-config-dashboards:
  grafana-data-dashboards:

networks:
  back-tier:

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file:
        - ../.env
    volumes:
      - grafana-data-config-datasources:/workspaces/Project_MLOPS/project-NicolaiDG/.grafana/datasources
      - grafana-data-config-dashboards:/workspaces/Project_MLOPS/project-NicolaiDG/.grafana/dashboards
      - grafana-data-dashboards:/workspaces/Project_MLOPS/project-NicolaiDG/dashboards
    network_mode: service:db
    command: sleep infinity

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
        - ../.env
    ports:
      - "5432:5432"
    networks:
      - back-tier

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - back-tier
